apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: object-store-minio
spec:
  type: bindings.aws.s3
  version: v1
  metadata:
    - name: bucket
      value: recordings
    - name: region
      value: us-east-1
    - name: endpoint
      value: http://localhost:9000
    - name: forcePathStyle
      value: true
    - name: disableSSL
      value: true
    - name: encodeBase64
      value: true
    - name: decodeBase64
      value: true
    - name: accessKey
      value: "GiJdOQ8uWFT5oM7UrxWg"
    - name: secretKey
      value: "5eOI4DRBeCvI3m2ycdDQPVyF8bvtOPRBnDORvRqs"